apiVersion: v1
kind: Pod
metadata:
  name: {{ include "vives.fullname" . }}
spec:
  containers:
  - name: test
    image: {{ .Values.image.repository }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    env:
      - name: MONGODB
        valueFrom:
          secretKeyRef:
            name: flask-pod-secret
            key: database_url
      - name: FLASK_ENV
        valueFrom:
          configMapKeyRef:
            name: flask-pod-configmap
            key: flask_env
      - name: FLASK_DEBUG
        valueFrom:
          configMapKeyRef:
            name: flask-pod-configmap
            key: flask_debug  
  imagePullSecrets:
  - name: regcred