apiVersion: v1
kind: Service
metadata:
  name: {{ include "vives.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: flask
